<?php
/**
 * Image.php
 * BaiSam BaiSam
 *
 * Created by realeff on 2018/09/29.
 * Copyright ©2018 Jiangxi baisam information technology co., LTD. All rights reserved.
 */


namespace BaiSam\UI\Grid\Render;


use BaiSam\UI\Grid\Render as AbstractRender;

class Image extends AbstractRender
{

    public function render($value, $row, $builder)
    {
        return parent::render($value, $row, $builder); // TODO: Change the autogenerated stub
    }

}